// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef CSCOREDLG2_H
#define CSCOREDLG2_H

#include <FL/Fl.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Double_Window.H>

#include <string>
#include <vector>

using namespace std;

class CHoleDescription {
 public:
  string hole;
  string yards;
  string hdcp;
  string par;
  CHoleDescription() : hole(""), yards(""), hdcp(""), par("") {}
  void setHoleDesc(const string h, const string y, const string c,
                   const string p) {
    hole = h;
    yards = y;
    hdcp = c;
    par = p;
  }
};

const int k19 = 19;

extern vector<CHoleDescription> vHoleDesc;

void initHoleDescVector();

class CScoreDlg2 : public Fl_Window {
 public:
  CScoreDlg2(int X, int Y, int W, int H, const char *L = 0);
  void updateHoleDescription(int n);

 private:
  int handle(int e);
};

extern void createScoreDlg2();
extern CScoreDlg2 *scoreDlg2;

// Fl_Double_Window* make_window();
#endif
