// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef CSCOREDLG2_H
#define CSCOREDLG2_H

#include <FL/Fl.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Double_Window.H>

#include <string>
#include <vector>

using namespace std;


class CScoreDlg2 : public Fl_Window {
 public:
  CScoreDlg2(int X, int Y, int W, int H, const char *L = 0);
  void updateHoleDescription(int n);

 private:
  int handle(int e);
  void stuffData(int n);

};

extern void createScoreDlg2();
extern CScoreDlg2 *scoreDlg2;

// Fl_Double_Window* make_window();
#endif
