// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef CSCOREDLG2_H
#define CSCOREDLG2_H
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>

extern Fl_Box *holeBox;
extern Fl_Box *yardsBox;
extern Fl_Box *hdcpBox;
extern Fl_Box *parBox;
extern Fl_Box *scoreBox;
extern Fl_Box *puttsBox;
extern Fl_Box *udBox;
extern Fl_Box *box0;
extern Fl_Box *box1;
extern Fl_Box *box2;
extern Fl_Box *box3;
extern Fl_Box *box4;
extern Fl_Box *box5;
extern Fl_Box *box6;
extern Fl_Box *box7;
extern Fl_Box *box8;
extern Fl_Box *box9;
extern Fl_Box *holeValue;
extern Fl_Box *yardsValue;
extern Fl_Box *hdcpValue;
extern Fl_Box *parValue;
extern Fl_Box *scoreValue;
extern Fl_Box *puttsValue;
extern Fl_Box *udValue;
extern Fl_Button *bntOK;
Fl_Double_Window* make_window();
#endif
