// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef CSCOREDLG2_H
#include "CScoreDlg2.h"
#endif
Fl_Box *holeBox=(Fl_Box *)0;

Fl_Box *yardsBox=(Fl_Box *)0;

Fl_Box *hdcpBox=(Fl_Box *)0;

Fl_Box *parBox=(Fl_Box *)0;

Fl_Box *scoreBox=(Fl_Box *)0;

Fl_Box *puttsBox=(Fl_Box *)0;

Fl_Box *udBox=(Fl_Box *)0;

Fl_Box *box0=(Fl_Box *)0;

Fl_Box *box1=(Fl_Box *)0;

Fl_Box *box2=(Fl_Box *)0;

Fl_Box *box3=(Fl_Box *)0;

Fl_Box *box4=(Fl_Box *)0;

Fl_Box *box5=(Fl_Box *)0;

Fl_Box *box6=(Fl_Box *)0;

Fl_Box *box7=(Fl_Box *)0;

Fl_Box *box8=(Fl_Box *)0;

Fl_Box *box9=(Fl_Box *)0;

Fl_Box *holeValue=(Fl_Box *)0;

Fl_Box *yardsValue=(Fl_Box *)0;

Fl_Box *hdcpValue=(Fl_Box *)0;

Fl_Box *parValue=(Fl_Box *)0;

Fl_Box *scoreValue=(Fl_Box *)0;

Fl_Box *puttsValue=(Fl_Box *)0;

Fl_Box *udValue=(Fl_Box *)0;

Fl_Button *bntOK=(Fl_Button *)0;

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(480, 735, "Score");
    w = o; if (w) {/* empty */}
    o->color((Fl_Color)159);
    { holeBox = new Fl_Box(60, 101, 90, 56, "Hole");
      holeBox->box(FL_BORDER_BOX);
      holeBox->color(FL_BACKGROUND2_COLOR);
      holeBox->selection_color(FL_BACKGROUND_COLOR);
      holeBox->labeltype(FL_NORMAL_LABEL);
      holeBox->labelfont(0);
      holeBox->labelsize(28);
      holeBox->labelcolor(FL_FOREGROUND_COLOR);
      holeBox->align(Fl_Align(FL_ALIGN_CENTER));
      holeBox->when(FL_WHEN_RELEASE);
    } // Fl_Box* holeBox
    { yardsBox = new Fl_Box(149, 101, 90, 56, "Yards");
      yardsBox->box(FL_BORDER_BOX);
      yardsBox->color(FL_BACKGROUND2_COLOR);
      yardsBox->selection_color(FL_BACKGROUND_COLOR);
      yardsBox->labeltype(FL_NORMAL_LABEL);
      yardsBox->labelfont(0);
      yardsBox->labelsize(28);
      yardsBox->labelcolor(FL_FOREGROUND_COLOR);
      yardsBox->align(Fl_Align(FL_ALIGN_CENTER));
      yardsBox->when(FL_WHEN_RELEASE);
    } // Fl_Box* yardsBox
    { hdcpBox = new Fl_Box(238, 101, 90, 56, "Hdcp");
      hdcpBox->box(FL_BORDER_BOX);
      hdcpBox->color(FL_BACKGROUND2_COLOR);
      hdcpBox->selection_color(FL_BACKGROUND_COLOR);
      hdcpBox->labeltype(FL_NORMAL_LABEL);
      hdcpBox->labelfont(0);
      hdcpBox->labelsize(28);
      hdcpBox->labelcolor(FL_FOREGROUND_COLOR);
      hdcpBox->align(Fl_Align(FL_ALIGN_CENTER));
      hdcpBox->when(FL_WHEN_RELEASE);
    } // Fl_Box* hdcpBox
    { parBox = new Fl_Box(327, 101, 90, 56, "Par");
      parBox->box(FL_BORDER_BOX);
      parBox->color(FL_BACKGROUND2_COLOR);
      parBox->selection_color(FL_BACKGROUND_COLOR);
      parBox->labeltype(FL_NORMAL_LABEL);
      parBox->labelfont(0);
      parBox->labelsize(28);
      parBox->labelcolor(FL_FOREGROUND_COLOR);
      parBox->align(Fl_Align(FL_ALIGN_CENTER));
      parBox->when(FL_WHEN_RELEASE);
    } // Fl_Box* parBox
    { scoreBox = new Fl_Box(105, 240, 90, 56, "Score");
      scoreBox->box(FL_BORDER_BOX);
      scoreBox->color(FL_BACKGROUND2_COLOR);
      scoreBox->selection_color(FL_BACKGROUND_COLOR);
      scoreBox->labeltype(FL_NORMAL_LABEL);
      scoreBox->labelfont(0);
      scoreBox->labelsize(28);
      scoreBox->labelcolor(FL_FOREGROUND_COLOR);
      scoreBox->align(Fl_Align(FL_ALIGN_CENTER));
      scoreBox->when(FL_WHEN_RELEASE);
    } // Fl_Box* scoreBox
    { puttsBox = new Fl_Box(194, 240, 90, 56, "Putts");
      puttsBox->box(FL_BORDER_BOX);
      puttsBox->color(FL_BACKGROUND2_COLOR);
      puttsBox->selection_color(FL_BACKGROUND_COLOR);
      puttsBox->labeltype(FL_NORMAL_LABEL);
      puttsBox->labelfont(0);
      puttsBox->labelsize(28);
      puttsBox->labelcolor(FL_FOREGROUND_COLOR);
      puttsBox->align(Fl_Align(FL_ALIGN_CENTER));
      puttsBox->when(FL_WHEN_RELEASE);
    } // Fl_Box* puttsBox
    { udBox = new Fl_Box(283, 240, 90, 56, "UD");
      udBox->box(FL_BORDER_BOX);
      udBox->color(FL_BACKGROUND2_COLOR);
      udBox->selection_color(FL_BACKGROUND_COLOR);
      udBox->labeltype(FL_NORMAL_LABEL);
      udBox->labelfont(0);
      udBox->labelsize(28);
      udBox->labelcolor(FL_FOREGROUND_COLOR);
      udBox->align(Fl_Align(FL_ALIGN_CENTER));
      udBox->when(FL_WHEN_RELEASE);
    } // Fl_Box* udBox
    { box0 = new Fl_Box(12, 410, 84, 100, "0");
      box0->box(FL_BORDER_BOX);
      box0->color(FL_BACKGROUND2_COLOR);
      box0->selection_color(FL_BACKGROUND_COLOR);
      box0->labeltype(FL_NORMAL_LABEL);
      box0->labelfont(0);
      box0->labelsize(60);
      box0->labelcolor(FL_FOREGROUND_COLOR);
      box0->align(Fl_Align(FL_ALIGN_CENTER));
      box0->when(FL_WHEN_RELEASE);
    } // Fl_Box* box0
    { box1 = new Fl_Box(105, 410, 84, 100, "1");
      box1->box(FL_BORDER_BOX);
      box1->color(FL_BACKGROUND2_COLOR);
      box1->selection_color(FL_BACKGROUND_COLOR);
      box1->labeltype(FL_NORMAL_LABEL);
      box1->labelfont(0);
      box1->labelsize(60);
      box1->labelcolor(FL_FOREGROUND_COLOR);
      box1->align(Fl_Align(FL_ALIGN_CENTER));
      box1->when(FL_WHEN_RELEASE);
    } // Fl_Box* box1
    { box2 = new Fl_Box(198, 410, 84, 100, "2");
      box2->box(FL_BORDER_BOX);
      box2->color(FL_BACKGROUND2_COLOR);
      box2->selection_color(FL_BACKGROUND_COLOR);
      box2->labeltype(FL_NORMAL_LABEL);
      box2->labelfont(0);
      box2->labelsize(60);
      box2->labelcolor(FL_FOREGROUND_COLOR);
      box2->align(Fl_Align(FL_ALIGN_CENTER));
      box2->when(FL_WHEN_RELEASE);
    } // Fl_Box* box2
    { box3 = new Fl_Box(291, 410, 84, 100, "3");
      box3->box(FL_BORDER_BOX);
      box3->color(FL_BACKGROUND2_COLOR);
      box3->selection_color(FL_BACKGROUND_COLOR);
      box3->labeltype(FL_NORMAL_LABEL);
      box3->labelfont(0);
      box3->labelsize(60);
      box3->labelcolor(FL_FOREGROUND_COLOR);
      box3->align(Fl_Align(FL_ALIGN_CENTER));
      box3->when(FL_WHEN_RELEASE);
    } // Fl_Box* box3
    { box4 = new Fl_Box(384, 410, 84, 100, "4");
      box4->box(FL_BORDER_BOX);
      box4->color(FL_BACKGROUND2_COLOR);
      box4->selection_color(FL_BACKGROUND_COLOR);
      box4->labeltype(FL_NORMAL_LABEL);
      box4->labelfont(0);
      box4->labelsize(60);
      box4->labelcolor(FL_FOREGROUND_COLOR);
      box4->align(Fl_Align(FL_ALIGN_CENTER));
      box4->when(FL_WHEN_RELEASE);
    } // Fl_Box* box4
    { box5 = new Fl_Box(12, 545, 84, 100, "5");
      box5->box(FL_BORDER_BOX);
      box5->color(FL_BACKGROUND2_COLOR);
      box5->selection_color(FL_BACKGROUND_COLOR);
      box5->labeltype(FL_NORMAL_LABEL);
      box5->labelfont(0);
      box5->labelsize(60);
      box5->labelcolor(FL_FOREGROUND_COLOR);
      box5->align(Fl_Align(FL_ALIGN_CENTER));
      box5->when(FL_WHEN_RELEASE);
    } // Fl_Box* box5
    { box6 = new Fl_Box(105, 545, 84, 100, "6");
      box6->box(FL_BORDER_BOX);
      box6->color(FL_BACKGROUND2_COLOR);
      box6->selection_color(FL_BACKGROUND_COLOR);
      box6->labeltype(FL_NORMAL_LABEL);
      box6->labelfont(0);
      box6->labelsize(60);
      box6->labelcolor(FL_FOREGROUND_COLOR);
      box6->align(Fl_Align(FL_ALIGN_CENTER));
      box6->when(FL_WHEN_RELEASE);
    } // Fl_Box* box6
    { box7 = new Fl_Box(198, 545, 84, 100, "7");
      box7->box(FL_BORDER_BOX);
      box7->color(FL_BACKGROUND2_COLOR);
      box7->selection_color(FL_BACKGROUND_COLOR);
      box7->labeltype(FL_NORMAL_LABEL);
      box7->labelfont(0);
      box7->labelsize(60);
      box7->labelcolor(FL_FOREGROUND_COLOR);
      box7->align(Fl_Align(FL_ALIGN_CENTER));
      box7->when(FL_WHEN_RELEASE);
    } // Fl_Box* box7
    { box8 = new Fl_Box(291, 545, 84, 100, "8");
      box8->box(FL_BORDER_BOX);
      box8->color(FL_BACKGROUND2_COLOR);
      box8->selection_color(FL_BACKGROUND_COLOR);
      box8->labeltype(FL_NORMAL_LABEL);
      box8->labelfont(0);
      box8->labelsize(60);
      box8->labelcolor(FL_FOREGROUND_COLOR);
      box8->align(Fl_Align(FL_ALIGN_CENTER));
      box8->when(FL_WHEN_RELEASE);
    } // Fl_Box* box8
    { box9 = new Fl_Box(384, 545, 84, 100, "9");
      box9->box(FL_BORDER_BOX);
      box9->color(FL_BACKGROUND2_COLOR);
      box9->selection_color(FL_BACKGROUND_COLOR);
      box9->labeltype(FL_NORMAL_LABEL);
      box9->labelfont(0);
      box9->labelsize(60);
      box9->labelcolor(FL_FOREGROUND_COLOR);
      box9->align(Fl_Align(FL_ALIGN_CENTER));
      box9->when(FL_WHEN_RELEASE);
    } // Fl_Box* box9
    { holeValue = new Fl_Box(60, 156, 90, 56);
      holeValue->box(FL_BORDER_BOX);
      holeValue->color(FL_BACKGROUND2_COLOR);
      holeValue->selection_color(FL_BACKGROUND_COLOR);
      holeValue->labeltype(FL_NORMAL_LABEL);
      holeValue->labelfont(0);
      holeValue->labelsize(28);
      holeValue->labelcolor(FL_FOREGROUND_COLOR);
      holeValue->align(Fl_Align(FL_ALIGN_CENTER));
      holeValue->when(FL_WHEN_RELEASE);
    } // Fl_Box* holeValue
    { yardsValue = new Fl_Box(149, 156, 90, 56);
      yardsValue->box(FL_BORDER_BOX);
      yardsValue->color(FL_BACKGROUND2_COLOR);
      yardsValue->selection_color(FL_BACKGROUND_COLOR);
      yardsValue->labeltype(FL_NORMAL_LABEL);
      yardsValue->labelfont(0);
      yardsValue->labelsize(28);
      yardsValue->labelcolor(FL_FOREGROUND_COLOR);
      yardsValue->align(Fl_Align(FL_ALIGN_CENTER));
      yardsValue->when(FL_WHEN_RELEASE);
    } // Fl_Box* yardsValue
    { hdcpValue = new Fl_Box(238, 156, 90, 56);
      hdcpValue->box(FL_BORDER_BOX);
      hdcpValue->color(FL_BACKGROUND2_COLOR);
      hdcpValue->selection_color(FL_BACKGROUND_COLOR);
      hdcpValue->labeltype(FL_NORMAL_LABEL);
      hdcpValue->labelfont(0);
      hdcpValue->labelsize(28);
      hdcpValue->labelcolor(FL_FOREGROUND_COLOR);
      hdcpValue->align(Fl_Align(FL_ALIGN_CENTER));
      hdcpValue->when(FL_WHEN_RELEASE);
    } // Fl_Box* hdcpValue
    { parValue = new Fl_Box(327, 156, 90, 56);
      parValue->box(FL_BORDER_BOX);
      parValue->color(FL_BACKGROUND2_COLOR);
      parValue->selection_color(FL_BACKGROUND_COLOR);
      parValue->labeltype(FL_NORMAL_LABEL);
      parValue->labelfont(0);
      parValue->labelsize(28);
      parValue->labelcolor(FL_FOREGROUND_COLOR);
      parValue->align(Fl_Align(FL_ALIGN_CENTER));
      parValue->when(FL_WHEN_RELEASE);
    } // Fl_Box* parValue
    { scoreValue = new Fl_Box(105, 295, 90, 56);
      scoreValue->box(FL_BORDER_BOX);
      scoreValue->color(FL_BACKGROUND2_COLOR);
      scoreValue->selection_color(FL_BACKGROUND_COLOR);
      scoreValue->labeltype(FL_NORMAL_LABEL);
      scoreValue->labelfont(0);
      scoreValue->labelsize(28);
      scoreValue->labelcolor(FL_FOREGROUND_COLOR);
      scoreValue->align(Fl_Align(FL_ALIGN_CENTER));
      scoreValue->when(FL_WHEN_RELEASE);
    } // Fl_Box* scoreValue
    { puttsValue = new Fl_Box(194, 295, 90, 56);
      puttsValue->box(FL_BORDER_BOX);
      puttsValue->color(FL_BACKGROUND2_COLOR);
      puttsValue->selection_color(FL_BACKGROUND_COLOR);
      puttsValue->labeltype(FL_NORMAL_LABEL);
      puttsValue->labelfont(0);
      puttsValue->labelsize(28);
      puttsValue->labelcolor(FL_FOREGROUND_COLOR);
      puttsValue->align(Fl_Align(FL_ALIGN_CENTER));
      puttsValue->when(FL_WHEN_RELEASE);
    } // Fl_Box* puttsValue
    { udValue = new Fl_Box(283, 295, 90, 56);
      udValue->box(FL_BORDER_BOX);
      udValue->color(FL_BACKGROUND2_COLOR);
      udValue->selection_color(FL_BACKGROUND_COLOR);
      udValue->labeltype(FL_NORMAL_LABEL);
      udValue->labelfont(0);
      udValue->labelsize(28);
      udValue->labelcolor(FL_FOREGROUND_COLOR);
      udValue->align(Fl_Align(FL_ALIGN_CENTER));
      udValue->when(FL_WHEN_RELEASE);
    } // Fl_Box* udValue
    { Fl_Box* o = new Fl_Box(60, 34, 90, 68, "Prev");
      o->labelfont(1);
      o->labelsize(24);
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(327, 37, 90, 65, "Next");
      o->labelfont(1);
      o->labelsize(24);
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(195, 25, 90, 65, "Hole");
      o->labelsize(28);
    } // Fl_Box* o
    { bntOK = new Fl_Button(174, 675, 140, 42, "OK");
      bntOK->color(FL_BACKGROUND2_COLOR);
      bntOK->labelsize(32);
    } // Fl_Button* bntOK
    o->set_modal();
    o->size_range(480, 735, 480, 735);
    o->end();
  } // Fl_Double_Window* o
  return w;
}
