// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef CSCORECARDDLG_H
#include "CScorecardDlg.h"
#endif

#ifndef CSCORECARD_H
#include "CScorecard.h"
#endif

#ifndef CGLOBALS_H
#include "globals.h"
#endif

#ifndef CFRONTBACKBTN_H
#include "CFrontBackBtn.h"
#endif

#ifndef CCLUBDLG_H
#include "CClubDlg.h"
#endif

CScorecardDlg *scorecardDlg = nullptr;
Fl_Button *okB = nullptr;
CFrontBackBtn *fbBtn = nullptr;
CScorecard *card = nullptr;
CClubDlg *clubDlg = nullptr;
Fl_Button *clubB = nullptr;

void okB_cb(Fl_Widget *w, void *data) { scorecardDlg->hide(); }

void clubB_cb(Fl_Widget *w, void *data) {
  clubDlg = new CClubDlg(0, 0, 480, 800);
}

CScorecardDlg::CScorecardDlg(int X, int Y, int W, int H, const char *L)
    : Fl_Window(X, Y, W, H, L) {
  const int kBtnW = 140;
  { card = new CScorecard(2, 20, 472, 244); }
  {
    okB = new Fl_Button(174, 675, kBtnW, kBtnH, "OK");
    setButtonStyle(okB);
    okB->callback(okB_cb, this);
  }
  {
    fbBtn = new CFrontBackBtn(190, 300, 0, 0);
    setButtonStyle(fbBtn);
  }
  {
    clubB = new Fl_Button(190, 358, kBtnW, kBtnH, "Clubs");
    setButtonStyle(clubB);
    clubB->callback(clubB_cb, this);
  }
  color((Fl_Color)159);
  set_modal();
  size_range(480, 800, 480, 800);
  end();
  show();
}

void createScorecardDlg() { scorecardDlg = new CScorecardDlg(0, 0, 480, 800); }
